name: Deploy-GAS
run-name: ${{ github.actor }} deploy GAS
on:
  workflow_call:
    inputs:
      SCRIPT_ID:
        required: true
        type: string 
    secrets:
      CLASPRC_JSON:
        required: true

jobs:
  deploy-GAS:
    runs-on: ubuntu-latest
    steps:
      - name: Install clasp
        id: install-clasp
        run: sudo npm install @google/clasp@2.4.1 -g

      - name: Check out repo
        id: check-out-repo
        uses: actions/checkout@v4

      - name: Write CLASPRC_JSON secret to  file
        id: write-clasprc
        run: |
            echo ${{ inputs.SCRIPT_ID }}
            echo "${{ secrets.CLASPRC_JSON }}" | base64 --decode >> ~/.clasprc.json
            clasp login --status
            cat ~/.clasprc.json

      - run: ls -al

      - name: Check clasp login status
        id: clasp_login
        run: clasp login --status
