name: Deploy-GAS
run-name: ${{ github.actor }} deploy GAS
on:
  workflow_call:
    inputs:
      SCRIPT_ID:
        required: true
        type: string 
      TEST_METHOD:
        required: true
        type: string 
    secrets:
      CLASPRC_JSON:
        required: true

jobs:
  deploy-GAS:
    runs-on: ubuntu-latest
    steps:
      - name: Install clasp
        id: install-clasp
        run: sudo npm install @google/clasp@2.4.1 -g

      - name: Check out repo
        id: check-out-repo
        uses: actions/checkout@v4

      - name: Write CLASPRC_LOGIN secret to  file
        id: write-clasprc-login
        run: |
            echo "${{ secrets.CLASPRC_LOGIN }}" | base64 --decode >> ~/.clasprc.json
            #clasp login --status
            cat ~/.clasprc.json

      - name: Check clasp login status
        id: clasp_login
        run: clasp login --status

      - name: Write CLASPRC_RUN secret to  file
        id: write-clasprc-run
        run: |
            echo "${{ secrets.CLASPRC_RUN }}" | base64 --decode >> .clasprc.json
            #clasp login --status
            cat .clasprc.json

      - name: prepare-clasp-json
        run: |
          export PWD=`pwd`
          echo '{"scriptId":"'${{ inputs.SCRIPT_ID }}'","rootDir":"'$PWD'","projectId":"${{ inputs.PROJECT_ID }}"}' >> .clasp.json
          cat .clasp.json

      - name: prepare-appscript-json
        run: |
          mv appsscript.json.prod appsscript.json
          ls -al

      - name: push
        run: clasp push -f

      - name: run-test
        run: |
          echo ${{ inputs.TEST_METHOD }}
          clasp run ${{ inputs.TEST_METHOD }}
      
      - name: deploy
        run: clasp deploy

      - run: ls -al

