name: Deploy-GAS
run-name: ${{ github.actor }} deploy GAS
on:
  workflow_call:
    inputs:
      SCRIPT_ID:
        required: true
        type: string 
    secrets:
      CLASPRC_JSON:
        required: true

jobs:
  deploy-GAS:
    runs-on: ubuntu-latest
    steps:
      - name: Install clasp
        id: install-clasp
        run: sudo npm install @google/clasp@2.4.1 -g

      - name: Check out repo
        id: check-out-repo
        uses: actions/checkout@v4

      - name: Write CLASPRC_JSON secret to  file
        id: write-clasprc
        run: |
            echo "${{ secrets.CLASPRC_JSON }}" | base64 --decode >> ~/.clasprc.json
            #clasp login --status
            cat ~/.clasprc.json

      - name: Check clasp login status
        id: clasp_login
        run: clasp login --status

      - name: prepare-clasp-json
        run: |
          export PWD=`pwd`
          echo '{"scriptId":"'${{ inputs.SCRIPT_ID }}'","rootDir":"'$PWD'"}' >> .clasp.json
          cat .clasp.json
          pwd
          ls -al
          ls -al ../
          ls -al ~/

      - name: push
        run: clasp push -f
      
      - name: deploy
        run: clasp deploy

      - run: ls -al

